### ISSUE TITLE
TableView column not drawing title on Snow Leopard when sorting.

### ISSUE THREAD

**Issue by jrhass** [timthedevguy/BGHUDAppKit#28] opened 2010-04-06 18:27 UTC
To demonstrate: 

Create an app which uses BGHUDTableView and bind it to an array controller. 
When you run the app, and click on the column to sort, the sort indicator draws correctly, but the title does not. 

This appears to only be on Snow Leopard, as this works as expected on Leopard. 

EDIT: posted pics

first launching the app: http://imgur.com/cS6CP.png

when sorting, no title: http://imgur.com/XR1P0.png

**Comment by timthedevguy** [comment] 2010-04-24 02:58
Ah ok, sorry, somehow this slid through the cracks of my email, my gmail got hacked recently, I see the problem and will get it resolved!

**Comment by jrhass** [comment] 2010-04-27 01:12
Oh great! Thank you very much -- sorry about your gmail!

**Comment by timthedevguy** [comment] 2010-05-06 22:25
Any chance you could send me a test project, I don't seem to be able to even get sort working on a regular tableview.... lol (binary dot god at gmail dot com)

**Comment by preble** [comment] 2010-05-14 22:20
I'm seeing the same thing.  Let me know if you need any additional info.  For what it's worth I'm not using bindings in my project.  Thanks.

**Comment by preble** [comment] 2010-06-29 23:14
Here is my hack/fix for the issue: a modification to BGHUDTableViewHeaderCell.m.  It's not pretty, it has only seen limited testing, and that testing was only on 10.6. http://gist.github.com/457967

**Comment by timthedevguy** [comment] 2010-08-29 02:25
Working on this problem right now, thanks for the example code preble, will be testing it as well.

**Comment by timthedevguy** [comment] 2010-08-29 03:40
Fixed: TableView column not drawing title

This fixes BGHUDTableView column headers that would
fail to draw when in a sorted state. Closed by c7bfe8cda3af12b352d85b55e025ed82b99f1eaa
- Was caused by drawing the table header background
  twice, once in _drawThemeContents and again in
  drawSortIndicatorWithFrame.  This covered up the drawn
  title.
- Also cleaned up the file by removing junk code.

**Closed as completed by timthedevguy** 2010-08-29 03:40 UTC
Labels: Fixed
